from typing import overload
import numpy

class Tensor:
    @overload
    def __init__(self, arg0: int, arg1: int) -> None: ...
    @overload
    def __init__(self, arg0: numpy.ndarray[numpy.float32]) -> None: ...
    def cols(self) -> int: ...
    def cpu(self) -> None: ...
    def data(self) -> float: ...
    def gpu(self) -> None: ...
    def gpuFree(self) -> None: ...
    def onCPU(self) -> bool: ...
    def rows(self) -> int: ...

def cpu_add(arg0: Tensor, arg1: Tensor) -> Tensor: ...
def gpu_add(arg0: Tensor, arg1: Tensor) -> Tensor: ...
